# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'SGPSIReader' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SGPSIReader
    pod 'AFNetworking', '~> 3.0'
    pod 'JSONModel', '~> 1.7'

  target 'SGPSIReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
